version: '3.8'

services:
  app:
    image: im4nt0/vrt-interface:latest
    container_name: vrt-interface
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "3000:3000"
    networks:
      - vrt-project-network-proxy

networks:
  vrt-project-network-proxy:
    external:
      name: vrtproject